### ISSUE TITLE
共享

### ISSUE THREAD

**Issue by tianyu1030** [31501102ygg/2019GraduationProject#1]
兄弟，可以共享一下你的数据库文件吗

**Comment by Lixianshengchao** [comment]
可以分享下数据库文件，可以在项目首页介绍添加 项目截图

**Comment by Volundio** [comment]
> 可以分享下数据库文件，可以在项目首页介绍添加 项目截图

那数据库文件呢，能分享下吗...

**Comment by 31501102ygg** [comment]
数据库没有导出，现在已经不在了，只有数据库表设计了
